//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS.Reading.StoryboardNavigatorTests {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IS.Reading.StoryboardNavigatorTests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;storyboard&gt;
        ///  &lt;viewpoint&gt;sulana&lt;/viewpoint&gt;
        ///  &lt;music&gt;never_look_back&lt;/music&gt;
        ///  &lt;background&gt;carmim&lt;/background&gt;
        ///
        ///  &lt;person&gt;ronam&lt;/person&gt;
        ///  &lt;emotion&gt;happy&lt;/emotion&gt;
        ///  &lt;voice&gt;Oi? Sou eu, Ronam, lembra?&lt;/voice&gt;
        ///  &lt;protagonist /&gt;
        ///  &lt;voice&gt;Tudo bem por aí?&lt;/voice&gt;
        ///  &lt;person&gt;ronam&lt;/person&gt;
        ///  &lt;emotion&gt;sad&lt;/emotion&gt;
        ///  &lt;voice&gt;Vou sobreviver, eu acho.&lt;/voice&gt;
        ///  &lt;reward&gt;+relationship&lt;/reward&gt;
        ///  &lt;emotion&gt;happy&lt;/emotion&gt;
        ///  &lt;voice&gt;Mas obrigado por perguntar.&lt;/voice [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Dialog {
            get {
                return ResourceManager.GetString("Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Dialog_Backward {
            get {
                return ResourceManager.GetString("Dialog_Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Dialog_Forward {
            get {
                return ResourceManager.GetString("Dialog_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;storyboard&gt;
        ///  &lt;viewpoint&gt;sulana&lt;/viewpoint&gt;
        ///  &lt;music&gt;never_look_back&lt;/music&gt;
        ///  &lt;background&gt;carmim&lt;/background&gt;
        ///  &lt;observe /&gt;
        ///  &lt;narration&gt;Capítulo 1: Fúria&lt;/narration&gt;
        ///
        ///  &lt;background&gt;transition&lt;/background&gt;
        ///
        ///  &lt;tutorial&gt;Esta história tem dois protagonistas: Sulana e Belísar.&lt;/tutorial&gt;
        ///  &lt;tutorial&gt;A narrativa irá alternar entre os pontos de vista de um e do outro.&lt;/tutorial&gt;
        ///  &lt;tutorial&gt;Você também terá a oportunidade de fazer escolhas no decorrer da hist [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- previous --
        ///OnTutorialOpen()
        ///OnTutorialChange(Cada opção sempre terá seus prós e contras. Escolha com sabedoria.)
        ///-- previous --
        ///OnTutorialChange(Você está prestes a fazer a sua primeira escolha.)
        ///-- previous --
        ///OnTutorialClose()
        ///OnNarrationOpen()
        ///OnNarrationChange(É algo visceral, profundamente enraizado dentro de você, uma necessidade absoluta, algo que não há como evitar.)
        ///-- previous --
        ///OnNarrationChange(Por mais que não goste dela, você não consegue evitá-la.)
        ///-- previous --
        ///OnNarrationC [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Introduction_Backward {
            get {
                return ResourceManager.GetString("Introduction_Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- next --
        ///OnProtagonistChange(sulana)
        ///OnMusicChange(never_look_back)
        ///OnBackgroundChange(carmim)
        ///-- next --
        ///OnNarrationOpen()
        ///OnNarrationChange(Capítulo 1: Fúria)
        ///-- next --
        ///OnNarrationClose()
        ///OnBackgroundChange(transition)
        ///OnTutorialOpen()
        ///OnTutorialChange(Esta história tem dois protagonistas: Sulana e Belísar.)
        ///-- next --
        ///OnTutorialChange(A narrativa irá alternar entre os pontos de vista de um e do outro.)
        ///-- next --
        ///OnTutorialChange(Você também terá a oportunidade de fazer escolhas no deco [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Introduction_Forward {
            get {
                return ResourceManager.GetString("Introduction_Forward", resourceCulture);
            }
        }
    }
}
